### ISSUE TITLE
Range Check Error

### ISSUE THREAD

**Issue by dioannidis** [Laksen/fp-ethernet#1]
Hi,

  if I enabled -Cr and/or -CR I get the following error : 

"fpethtcp.pas(232,30) Error: Range check error while evaluating constants (864 must be between -128 and 127)"

I'm using ppcrossavr fpc rev. 42273 builded with "-g -gw2 -godwarfsets -O1" on Windows 10 and AVR_8_bit_GNU_Toolchain_3.6.2_1759. 

The project build options are " G:\Programming\dimitris\tools\fpc-trunk\bin\x86_64-win64\fpc.exe
-Tembedded
-Pavr
-CpAVR5
-MObjFPC
-Si
-CirotR
-Ch1500
-O1
-gw2
-godwarfsets
-Xg
-Xs
-l
-vewnhibq
-Filib\avr-embedded
-Fu..\source
-Fu..\fp-ethernet
-Fu.
-FUlib\avr-embedded
-FE.
-oavrFP_ENC28J60_Test
-WpATMEGA328P
-XPavr-
-FDG:\Programming\dimitris\tools\avr8-gnu-toolchain\bin
-al
-Xe
-Xm
-dF_CPU:=16000000
-dDEBUGUNITS
-dFP_ENC28J60_USEINTERRUPT"

Is it something that is expected ? Is an fpc bug  ?

**Comment by Laksen** [comment]
It's a compiler bug, yes

**Comment by dioannidis** [comment]
Just tested fpc rev. 42333. The range check error is fixed. Thanks !

**Comment by Laksen** [comment]
Hehe, that shouldn't have fixed it. But nice.. :)

I just committed a fix for the underlying sizeof issue in r42337
